/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectdoctorappointmentsystem;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.Map;
/**
 *
 * @author DaddyK
 */
public class BookPatientForm extends javax.swing.JFrame {
private boolean UEM;
private boolean MP;


    /**
     * Creates new form BookPatientForm
     */
    public BookPatientForm() {
        initComponents();
        
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);    
        jButton3.setVisible(false); 
        IDHolder.setVisible(false);
        BPname1.setVisible(false);
        qw1.setVisible(false);
        qw2.setVisible(false);
        BPtz1.setVisible(false);
        qw3.setVisible(false);
        qw4.setVisible(false);
        qw5.setVisible(false);
        qw6.setVisible(false);
        BPname.setVisible(false);
        BPtz.setVisible(false);
        BPs.setVisible(false);
        BPe.setVisible(false);
        
        
        qw7.setVisible(false);
        qw8.setVisible(false);
        PUname.setVisible(false);
        PEmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPane = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BPname = new javax.swing.JTextField();
        qw3 = new javax.swing.JLabel();
        BPtz = new javax.swing.JTextField();
        qw4 = new javax.swing.JLabel();
        BPs = new javax.swing.JTextField();
        qw5 = new javax.swing.JLabel();
        BPe = new javax.swing.JTextField();
        qw6 = new javax.swing.JLabel();
        BPname1 = new javax.swing.JTextField();
        qw1 = new javax.swing.JLabel();
        BPtz1 = new javax.swing.JTextField();
        qw2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PEmail = new javax.swing.JTextField();
        qw7 = new javax.swing.JLabel();
        PUname = new javax.swing.JTextField();
        qw8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        IDHolder = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Gmail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTableMouseClicked(evt);
            }
        });
        SearchPane.setViewportView(SearchTable);

        jButton1.setText("Search Doctors");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        qw3.setText("Name");

        BPtz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPtzActionPerformed(evt);
            }
        });

        qw4.setText("TimeZone");

        qw5.setText("Start");

        qw6.setText("End");

        qw1.setText("Username");

        BPtz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPtz1ActionPerformed(evt);
            }
        });

        qw2.setText("Gmail");

        jButton2.setText("Find Doctor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Book this Appointment!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        PEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEmailActionPerformed(evt);
            }
        });

        qw7.setText("Patients Email");

        qw8.setText("Patients Username");

        jButton3.setText("Select Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Continue");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(313, 313, 313))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw8)
                                    .addComponent(PUname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw1)
                                    .addComponent(BPname1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BPtz1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))))
                            .addComponent(jButton1)
                            .addComponent(SearchPane, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw3)
                                    .addComponent(BPname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw4)
                                    .addComponent(BPtz, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(qw5)
                                        .addGap(102, 102, 102))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BPs)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BPe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButton3)))))
                        .addContainerGap(99, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(SearchPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BPtz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPtz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qw7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(IDHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LandingPage p1 = new LandingPage();  // You should use your actual instance creation logic

        DefaultTableModel modelTwo = (DefaultTableModel) SearchTable.getModel();

    // Clear existing rows from SearchTable
    modelTwo.setRowCount(0);

    // Iterate through the data map and add each entry to SearchTable
    for (Map.Entry<String, String[]> entry : Database_ScheduleOfDoctor.DoctorScheduleDatabase.data.entrySet()) {
        String user = entry.getKey();
        String[] userData = entry.getValue();

        // Extract the relevant data from the userData array
        String username = userData[0];
        String gmail = userData[3];

        // Add the data to SearchTable
        modelTwo.addRow(new Object[]{user, username, gmail});
    }
        
       /* Original Method
        DefaultTableModel modelOne = (DefaultTableModel) p1.DocStoreBookTable.getModel();
        DefaultTableModel modelTwo = (DefaultTableModel) SearchTable.getModel();

     Iterate through each row in tableone and add it to tabletwo
    for (int row = 0; row < modelOne.getRowCount(); row++) {
        String test1 = modelOne.getValueAt(row, 0).toString(); //using this
        String test2 = modelOne.getValueAt(row, 1).toString(); //using this
        String test3 = modelOne.getValueAt(row, 2).toString(); //un-used
        String test4 = modelOne.getValueAt(row, 3).toString(); //un-used
        String test5 = modelOne.getValueAt(row, 4).toString(); //un-used
        String test6 = modelOne.getValueAt(row, 5).toString(); //un-used
        String test7 = modelOne.getValueAt(row, 6).toString(); //using this
        String test8 = modelOne.getValueAt(row, 7).toString(); //un-used

        // Add the data to tabletwo
        modelTwo.addRow(new Object[]{ test1, test2, test7});
        
    }*/
    qw1.setVisible(true);
    qw2.setVisible(true);
    BPname1.setVisible(true);
    BPtz1.setVisible(true);
    jButton2.setVisible(true);
    jButton1.setEnabled(false);    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel p10 = (DefaultTableModel)SearchTable.getModel();
        int selectedRowIndex = SearchTable.getSelectedRow();
        BPname1.setText(p10.getValueAt(selectedRowIndex, 1).toString());
        BPtz1.setText(p10.getValueAt(selectedRowIndex, 2).toString());
        IDHolder.setText(p10.getValueAt(selectedRowIndex, 0).toString());
        
        
    }//GEN-LAST:event_SearchTableMouseClicked

    private void BPtz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPtz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPtz1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String user = BPname1.getText();
        String email = BPtz1.getText();

        // Check if the data exists in the database
        if (Database_ScheduleOfDoctor.DoctorScheduleDatabase.checkDATA(user, email)) {
            // If it exists, retrieve the information
            String[] userData = Database_ScheduleOfDoctor.DoctorScheduleDatabase.data.get(user);

            // Extract the relevant information
            String name = userData[2];
            String timezone = userData[4];
            String start = userData[5];
            String end = userData[6];

            // Set the values to the corresponding JTextFields
            BPname.setText(name);
            BPtz.setText(timezone);
            BPs.setText(start);
            BPe.setText(end);
            qw3.setVisible(true);
            qw4.setVisible(true);
            qw5.setVisible(true);
            qw6.setVisible(true);
            BPname.setVisible(true);
            BPtz.setVisible(true);
            BPs.setVisible(true);
            BPe.setVisible(true);
            jButton3.setVisible(true);
        } else {
            // Handle the case where the data doesn't exist
            // For example, you can display a message or clear the text fields
            BPname.setText("Not found");
            BPtz.setText("");
            BPs.setText("");
            BPe.setText("");
            JOptionPane.showMessageDialog(null, "Doctor Has not set his Schedule, Please Try again on a later time.");
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        UEM = Database_PatientToSecretary.PatientApplicationDatabase.checkValidUser_Email(PUname.getText(), PEmail  .getText());
        if (UEM){
        Database_BookingPatientToDoctor.Relationship_BetweenEntities.Keep(IDHolder.getText(), BPname1.getText(), BPtz1.getText(), PUname.getText(), PEmail.getText(), BPtz.getText(), BPs.getText(), BPe.getText());
        jButton4.setVisible(false);
        jButton5.setVisible(true);
        JOptionPane.showMessageDialog(null, "Book have succesfully Stored Please check you Gmail on a later time");
        } else {
            JOptionPane.showMessageDialog(null, "Please Use your designated account!");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PEmailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        SearchTable.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setVisible(true);
        qw7.setVisible(true);
        qw8.setVisible(true);
        PUname.setVisible(true);
        PEmail.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Database_PatientTime_DoctorSched.PATtime_DocSched.TimeKeeper(BPname1.getText(), BPtz1.getText(), BPtz.getText(), BPs.getText(), BPe.getText(), PUname.getText(), PEmail.getText());
        JOptionPane.showMessageDialog(null, "The Secretary will message you If He/She have accepted from your Doctor");
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BPtzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPtzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPtzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPe;
    private javax.swing.JTextField BPname;
    private javax.swing.JTextField BPname1;
    private javax.swing.JTextField BPs;
    private javax.swing.JTextField BPtz;
    private javax.swing.JTextField BPtz1;
    private javax.swing.JTextField IDHolder;
    private javax.swing.JTextField PEmail;
    private javax.swing.JTextField PUname;
    public javax.swing.JScrollPane SearchPane;
    public javax.swing.JTable SearchTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel qw1;
    private javax.swing.JLabel qw2;
    private javax.swing.JLabel qw3;
    private javax.swing.JLabel qw4;
    private javax.swing.JLabel qw5;
    private javax.swing.JLabel qw6;
    private javax.swing.JLabel qw7;
    private javax.swing.JLabel qw8;
    // End of variables declaration//GEN-END:variables
}
